services:
  postgres:
    image: postgres:16-alpine
    container_name: ru-sivak-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: car_dealership
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d car_dealership" ]
      interval: 10s
      timeout: 5s
      retries: 5
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"
    restart: always
volumes:
  postgres_data:
